### ISSUE TITLE
Bug: Raw data frequency

### ISSUE THREAD

**Issue by InterMet-Admin** [InterMet-Systems/Met-GC#38]
Tested with commit https://github.com/InterMet-Systems/Met-GC/commit/6f124f722385cebb729c0f52d26313b8c607125b and FN24.

The timing is likely wrong. One line of raw data should be created every time the data balancer is able to find at least one of each data entry. I expected this to be at about 4 Hz. Right now it is 1-2 Hz.

[RAW_05-20-2024_09-35-38.txt](https://github.com/InterMet-Systems/Met-GC/files/15377893/RAW_05-20-2024_09-35-38.txt)

**Comment by Travis-Dunn** [comment]
Seems to be a product of the frequency of the mavlink messages, which is out of the scope of this project, although not an intractable problem. Solution may lie in UAV firmware, as it needs to send messages more often. Alternately, we could amend the requirement to have a new copy of each mavlink message to form a new "Balanced data line".
