### ISSUE TITLE
Rev 14: Raw Data File Persistence

### ISSUE THREAD

**Issue by InterMet-Admin** [InterMet-Systems/Met-GC#44]
Commit 2fe3ceb2b49e0a61d8da16d277a88cbe078f4f89.

A single raw data file should only contain information from a single vehicle connection.
How it should be:
Connect to vehicle > do flight > do flight > disconnect = 1 raw data file with 2 flights of data in it
Connect to vehicle > do flight > disconnect > do flight > disconnect = 2 raw data files with 1 flight each in them

**Comment by vfasburg** [comment]
note to self: use _activeVehicle to make this distinction (not armed, which is used for other message files)
